service: lambaa-demo
useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    region: us-west-2
    lambdaHashingVersion: "20201221"

functions:
    lambaa-router:
        handler: src/index.handler
        events:
            - http:
                  path: ping
                  method: ANY
                  cors: true

plugins:
    - serverless-webpack

custom:
    webpack:
        webpackConfig: "./webpack.config.js"
        includeModules: true
